# BookVerse Infrastructure Version Configuration  
# Dual-Build Aggregation Pattern: Multiple builds → Single application
# Supports: bookverse-core (Python) + bookverse-devops (Generic) → bookverse-infra app

applications:
  - key: bookverse-infra
    seeds:
      application: 1.0.3  # Random seed for infrastructure application
    packages:
      # Packages from bookverse-core build (Python library)
      - type: python
        name: bookverse-core  
        seed: 0.1.7  # Random seed for core library
      
      # Packages from bookverse-devops build (DevOps tooling) - TEMP: using python type for testing
      - type: python
        name: bookverse-devops
        seed: 1.0.9  # Random seed for devops package
