
applications:
  - key: bookverse-infra
    seeds:
      application: 1.0.3
    packages:
      - type: python
        name: bookverse-core  
        seed: 2.1.7
      
      - type: generic
        name: bookverse-devops
        seed: 1.0.9
