name: Generate Enhanced OIDC Token
description: Generate OIDC token with application key scope using JFrog CLI and enhanced metadata
author: BookVerse Platform Team

inputs:
  oidc-provider-url:
    description: 'OIDC provider URL (JFrog URL)'
    required: true
  oidc-provider-name:
    description: 'OIDC provider name (e.g., bookverse-inventory-github)'
    required: true
  oidc-audience:
    description: 'OIDC audience'
    required: false
  service-name:
    description: 'Service name for metadata'
    required: true
  application-key:
    description: 'Application key for scoping'
    required: true
  version:
    description: 'Version for metadata'
    required: false
    default: 'latest'
  project-key:
    description: 'Project key for scoping'
    required: false
    default: 'bookverse'

outputs:
  auth-user:
    description: 'Authenticated user'
    value: ${{ steps.auth-token-generation.outputs.oidc-user }}
  auth-token:
    description: 'OIDC access token'
    value: ${{ steps.enhanced-token-exchange.outputs.enhanced-token }}
  token-metadata:
    description: 'Token metadata information'
    value: ${{ steps.enhanced-token-exchange.outputs.token-metadata }}

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        echo "🔍 Validating OIDC token generation inputs..."
        echo "  • Provider URL: ${{ inputs.oidc-provider-url }}"
        echo "  • Provider Name: ${{ inputs.oidc-provider-name }}"
        echo "  • Service: ${{ inputs.service-name }}"
        echo "  • Application: ${{ inputs.application-key }}"
        echo "  • Version: ${{ inputs.version }}"
        echo "  • Project: ${{ inputs.project-key }}"
        
        # Validate required GitHub Actions environment
        if [[ -z "${ACTIONS_ID_TOKEN_REQUEST_URL:-}" || -z "${ACTIONS_ID_TOKEN_REQUEST_TOKEN:-}" ]]; then
          echo "❌ Missing GitHub OIDC environment variables"
          echo "   ACTIONS_ID_TOKEN_REQUEST_URL: ${ACTIONS_ID_TOKEN_REQUEST_URL:+SET}"
          echo "   ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${ACTIONS_ID_TOKEN_REQUEST_TOKEN:+SET}"
          exit 1
        fi
        
        echo "✅ Input validation completed"

    - name: Use JFrog CLI for Base Authentication (OIDC)
      id: auth-token-generation
      uses: EyalDelarea/setup-jfrog-cli@swampUpAppTrust
      env:
        JF_URL: ${{ inputs.oidc-provider-url }}
      with:
        oidc-provider-name: ${{ inputs.oidc-provider-name }}
        oidc-audience: ${{ inputs.oidc-audience || inputs.oidc-provider-url }}

    - name: Verify Token and Set Docker Authentication
      shell: bash
      run: |
        echo "🔍 Verifying enhanced OIDC token..."
        
        # Debug: Check available JFrog-related environment variables
        echo "🔍 Checking available JFrog environment variables..."
        env | grep -i jf | head -10 || echo "No JF environment variables found"
        
        # Try different possible token variable names
        if [[ -n "${JF_OIDC_TOKEN:-}" ]]; then
          TOKEN="$JF_OIDC_TOKEN"
          echo "✅ Using JF_OIDC_TOKEN"
        elif [[ -n "${JF_ACCESS_TOKEN:-}" ]]; then
          TOKEN="$JF_ACCESS_TOKEN"
          echo "✅ Using JF_ACCESS_TOKEN"
        elif [[ -n "${JFROG_CLI_ACCESS_TOKEN:-}" ]]; then
          TOKEN="$JFROG_CLI_ACCESS_TOKEN"
          echo "✅ Using JFROG_CLI_ACCESS_TOKEN"
        else
          echo "❌ No JFrog token found in environment variables"
          exit 1
        fi
        
        # Test token with JFrog ping
        if curl -sS -f -H "Authorization: Bearer $TOKEN" \
           "${{ inputs.oidc-provider-url }}/artifactory/api/system/ping" > /dev/null; then
          echo "✅ Enhanced OIDC token verified successfully"
        else
          echo "❌ Enhanced OIDC token verification failed"
          exit 1
        fi
        
        # Extract Docker registry from JFrog URL if needed
        DOCKER_REGISTRY="${{ inputs.oidc-provider-url }}"
        DOCKER_REGISTRY="${DOCKER_REGISTRY#https://}"
        DOCKER_REGISTRY="${DOCKER_REGISTRY#http://}"
        
        # Extract username from JWT token for Docker login
        TOKEN_PAYLOAD=$(echo "$TOKEN" | cut -d. -f2)
        # Add padding if needed
        case $((${#TOKEN_PAYLOAD} % 4)) in
          2) TOKEN_PAYLOAD="${TOKEN_PAYLOAD}==" ;;
          3) TOKEN_PAYLOAD="${TOKEN_PAYLOAD}=" ;;
        esac
        
        CLAIMS=$(echo "$TOKEN_PAYLOAD" | tr '_-' '/+' | base64 -d 2>/dev/null || true)
        DOCKER_USER=$(echo "$CLAIMS" | jq -r '.username // .sub // .subject // "oauth2_access_token"' 2>/dev/null || echo "oauth2_access_token")
        
        # If sub is in the form jfac@.../users/<username>, extract the trailing <username>
        if [[ "$DOCKER_USER" == *"/users/"* ]]; then
          DOCKER_USER=${DOCKER_USER##*/users/}
        fi
        
        # Fallback to oauth2_access_token if no username found
        if [[ -z "$DOCKER_USER" || "$DOCKER_USER" == "null" ]]; then
          DOCKER_USER="oauth2_access_token"
        fi
        
        echo "🐳 Configuring Docker authentication..."
        echo "  • Registry: $DOCKER_REGISTRY"
        echo "  • Username: $DOCKER_USER"
        echo "  • Token: ${TOKEN:0:10}... (truncated for security)"
        
        # Perform Docker login (non-interactive)
        if ! echo "$TOKEN" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USER" --password-stdin 2>/dev/null; then
          echo "⚠️ Standard Docker login failed, trying alternative approach..."
          # Alternative approach: use docker config directly
          mkdir -p ~/.docker
          DOCKER_AUTH=$(echo -n "${DOCKER_USER}:${TOKEN}" | base64 -w 0)
          cat > ~/.docker/config.json << 'DOCKER_CONFIG_EOF'
        {
          "auths": {
            "${DOCKER_REGISTRY}": {
              "auth": "${DOCKER_AUTH}"
            }
          }
        }
        DOCKER_CONFIG_EOF
          # Replace variables in the config file
          sed -i "s/\${DOCKER_REGISTRY}/${DOCKER_REGISTRY}/g" ~/.docker/config.json
          sed -i "s/\${DOCKER_AUTH}/${DOCKER_AUTH}/g" ~/.docker/config.json
          echo "✅ Docker authentication configured via config file"
        else
          echo "✅ Docker authentication configured via login command"
        fi
        
        # Verify Docker authentication works
        echo "🔍 Verifying Docker authentication..."
        if docker info > /dev/null 2>&1; then
          echo "✅ Docker daemon is accessible"
        else
          echo "⚠️ Docker daemon not accessible, but authentication may still work for builds"
        fi
        
        echo "✅ Docker authentication configured successfully"

branding:
  icon: 'lock'
  color: 'blue'
