
evidence_matrix:
  
  package_evidence:
    
    docker:
      - name: "pytest-results"
        predicate_type: "https://pytest.org/evidence/results/v1"
        description: "Unit test results and coverage from pytest"
        required: true
        
      - name: "sast-scan"
        predicate_type: "https://checkmarx.com/evidence/sast/v1.1"
        description: "Static Application Security Testing results"
        required: true
    
    python:
      - name: "pytest-results"
        predicate_type: "https://pytest.org/evidence/results/v1"
        description: "Unit test results and coverage from pytest"
        required: true
    
    generic:
      - name: "config-bundle"
        predicate_type: "Artifact Bundle"
        description: "Configuration and resource bundle verification (tar.gz files)"
        required: true

  build_evidence:
    
    - name: "fossa-license-scan"
      predicate_type: "https://fossa.com/evidence/license-scan/v2.1"
      description: "License compliance scan results for all dependencies"
      required: true
      
    - name: "sonar-quality-gate"
      predicate_type: "https://sonarsource.com/evidence/quality-gate/v1"
      description: "Code quality analysis and quality gate results"
      required: true

  application_evidence:
    
    unassigned:
      - name: "slsa-provenance"
        predicate_type: "https://slsa.dev/provenance/v1"
        description: "SLSA provenance for supply chain security"
        required: true
        attach_stage: "UNASSIGNED"
        gate_for_promotion_to: "DEV"
        
      - name: "jira-release"
        predicate_type: "https://atlassian.com/evidence/jira/release/v1"
        description: "Jira release notes and ticket tracking"
        required: true
        attach_stage: "UNASSIGNED"
        gate_for_promotion_to: "DEV"
    
    dev:
      - name: "smoke-tests"
        predicate_type: "https://bookverse.com/evidence/smoke-tests/v1"
        description: "Basic smoke tests in DEV environment"
        required: false
        attach_stage: "DEV"
        gate_for_promotion_to: "QA"
    
    qa:
      - name: "dast-scan"
        predicate_type: "https://invicti.com/evidence/dast/v3"
        description: "Dynamic Application Security Testing results"
        required: false
        attach_stage: "QA"
        gate_for_promotion_to: "STAGING"
        
      - name: "api-tests"
        predicate_type: "https://postman.com/evidence/collection/v2.2"
        description: "API integration test results"
        required: false
        attach_stage: "QA"
        gate_for_promotion_to: "STAGING"
    
    staging:
      - name: "iac-scan"
        predicate_type: "https://snyk.io/evidence/iac/v1"
        description: "Infrastructure as Code security scan"
        required: true
        attach_stage: "STAGING"
        gate_for_promotion_to: "PROD"
        
      - name: "pentest"
        predicate_type: "https://cobalt.io/evidence/pentest/v1"
        description: "Penetration testing results"
        required: true
        attach_stage: "STAGING"
        gate_for_promotion_to: "PROD"
        
      - name: "change-approval"
        predicate_type: "https://servicenow.com/evidence/change-req/v1"
        description: "Change management approval"
        required: true
        attach_stage: "STAGING"
        gate_for_promotion_to: "PROD"
    
    prod:
      - name: "deployment-verification"
        predicate_type: "https://argoproj.github.io/evidence/deployment/v1"
        description: "Production deployment verification and health checks"
        required: false
        attach_stage: "PROD"
        gate_for_promotion_to: null
